// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.FeeCalculator.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BankCardsFeeResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the BankCardsFeeResponseModel class.
        /// </summary>
        public BankCardsFeeResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BankCardsFeeResponseModel class.
        /// </summary>
        public BankCardsFeeResponseModel(double percentage)
        {
            Percentage = percentage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Percentage")]
        public double Percentage { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
