// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.FeeCalculator.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CashoutFee
    {
        /// <summary>
        /// Initializes a new instance of the CashoutFee class.
        /// </summary>
        public CashoutFee()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CashoutFee class.
        /// </summary>
        /// <param name="type">Possible values include: 'Unknown', 'Absolute',
        /// 'Relative'</param>
        public CashoutFee(double size, FeeType type, string id = default(string), string assetId = default(string))
        {
            Id = id;
            AssetId = assetId;
            Size = size;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public double Size { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Absolute',
        /// 'Relative'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public FeeType Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
