// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.FeeCalculator.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MarketOrderFeeResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the MarketOrderFeeResponseModel
        /// class.
        /// </summary>
        public MarketOrderFeeResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MarketOrderFeeResponseModel
        /// class.
        /// </summary>
        public MarketOrderFeeResponseModel(double defaultFeeSize)
        {
            DefaultFeeSize = defaultFeeSize;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DefaultFeeSize")]
        public double DefaultFeeSize { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
