// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.FeeCalculator.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PaymentSystemType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PaymentSystemType
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Sepa")]
        Sepa,
        [EnumMember(Value = "Swift")]
        Swift,
        [EnumMember(Value = "Swiss")]
        Swiss
    }
    internal static class PaymentSystemTypeEnumExtension
    {
        internal static string ToSerializedValue(this PaymentSystemType? value)
        {
            return value == null ? null : ((PaymentSystemType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PaymentSystemType value)
        {
            switch( value )
            {
                case PaymentSystemType.Unknown:
                    return "Unknown";
                case PaymentSystemType.Sepa:
                    return "Sepa";
                case PaymentSystemType.Swift:
                    return "Swift";
                case PaymentSystemType.Swiss:
                    return "Swiss";
            }
            return null;
        }

        internal static PaymentSystemType? ParsePaymentSystemType(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return PaymentSystemType.Unknown;
                case "Sepa":
                    return PaymentSystemType.Sepa;
                case "Swift":
                    return PaymentSystemType.Swift;
                case "Swiss":
                    return PaymentSystemType.Swiss;
            }
            return null;
        }
    }
}
