// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.FeeCalculator.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WithdrawalFeeModel
    {
        /// <summary>
        /// Initializes a new instance of the WithdrawalFeeModel class.
        /// </summary>
        public WithdrawalFeeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WithdrawalFeeModel class.
        /// </summary>
        /// <param name="paymentSystem">Possible values include: 'Unknown',
        /// 'Sepa', 'Swift', 'Swiss'</param>
        public WithdrawalFeeModel(double size, PaymentSystemType paymentSystem, string assetId = default(string))
        {
            AssetId = assetId;
            Size = size;
            PaymentSystem = paymentSystem;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public double Size { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Sepa', 'Swift',
        /// 'Swiss'
        /// </summary>
        [JsonProperty(PropertyName = "PaymentSystem")]
        public PaymentSystemType PaymentSystem { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
