// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.FeeCalculator.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WithdrawalFeeModel
    {
        /// <summary>
        /// Initializes a new instance of the WithdrawalFeeModel class.
        /// </summary>
        public WithdrawalFeeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WithdrawalFeeModel class.
        /// </summary>
        /// <param name="paymentSystemForSelectedCountries">Possible values
        /// include: 'Unknown', 'Sepa', 'Swift', 'Swiss'</param>
        /// <param name="paymentSystemForOtherCountries">Possible values
        /// include: 'Unknown', 'Sepa', 'Swift', 'Swiss'</param>
        public WithdrawalFeeModel(double sizeForSelectedCountries, double sizeForOtherCountries, PaymentSystemType paymentSystemForSelectedCountries, PaymentSystemType paymentSystemForOtherCountries, string assetId = default(string), IList<string> countries = default(IList<string>))
        {
            AssetId = assetId;
            SizeForSelectedCountries = sizeForSelectedCountries;
            SizeForOtherCountries = sizeForOtherCountries;
            Countries = countries;
            PaymentSystemForSelectedCountries = paymentSystemForSelectedCountries;
            PaymentSystemForOtherCountries = paymentSystemForOtherCountries;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SizeForSelectedCountries")]
        public double SizeForSelectedCountries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SizeForOtherCountries")]
        public double SizeForOtherCountries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Countries")]
        public IList<string> Countries { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Sepa', 'Swift',
        /// 'Swiss'
        /// </summary>
        [JsonProperty(PropertyName = "PaymentSystemForSelectedCountries")]
        public PaymentSystemType PaymentSystemForSelectedCountries { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Sepa', 'Swift',
        /// 'Swiss'
        /// </summary>
        [JsonProperty(PropertyName = "PaymentSystemForOtherCountries")]
        public PaymentSystemType PaymentSystemForOtherCountries { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
